# Numpy

In [0]:
import numpy as np

Creating the array:

In [4]:
array_a = np.array([1,2,3,4,5])
print(f"Ärray a is:\n{array_a}", "\n")

array_a = np.arange(1, 6, 1) #third value is increment
print(f"Ärray a is:\n{array_a}")

array_a = np.linspace(1, 6, 5)
print(f"Ärray a is:\n{array_a}") #third value is number of values with constant increment

Ärray a is:
[1 2 3 4 5] 

Ärray a is:
[1 2 3 4 5]
Ärray a is:
[1.   2.25 3.5  4.75 6.  ]


We can check shape, size,, dimension, data type of array (as if we get these parameters of a matrix):

In [0]:
array_b = np.array([[1,2,3,4], [5, 6, 7, 8], [9,10,11,12], [13, 14, 15, 16]])
print(f"Ärray b is:\n{array_b}")

print(f"Shape of array b is: {array_b.shape}")
print(f"Size of array b is: {array_b.size}")
print(f"Dimension of array b is: {array_b.ndim}")
print(f"Data type of array b is: {array_b.dtype}")

Ärray b is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Shape of array b is: (4, 4)
Size of array b is: 16
Dimension of array b is: 2
Data type of array b is: int64


We can reshape the array in many different ways:

In [0]:
array_b_t = array_b.reshape(8, 2)
print(f"Reshape of array b is:\n{array_b_t}")
print(f"Shape of reshape of array b is: {array_b_t.shape}")
print(f"Size of reshape of array b is: {array_b_t.size}", "\n")

array_b_t = array_b.reshape(2, 8)
print(f"Reshape of array b is:\n{array_b_t}")
print(f"Shape of reshape of array b is: {array_b_t.shape}")
print(f"Size of reshape of array b is: {array_b_t.size}", "\n")

array_b_t = array_b.reshape(1, 16)
print(f"Reshape of array b is:\n{array_b_t}")
print(f"Shape of reshape of array b is: {array_b_t.shape}")
print(f"Size of reshape of array b is: {array_b_t.size}", "\n")

array_b_t = array_b.reshape(16, 1)
print(f"Reshape of array b is:\n{array_b_t}")
print(f"Shape of reshape of array b is: {array_b_t.shape}")
print(f"Size of reshape of array b is: {array_b_t.size}")

Reshape of array b is:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
Shape of reshape of array b is: (8, 2)
Size of reshape of array b is: 16 

Reshape of array b is:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
Shape of reshape of array b is: (2, 8)
Size of reshape of array b is: 16 

Reshape of array b is:
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]
Shape of reshape of array b is: (1, 16)
Size of reshape of array b is: 16 

Reshape of array b is:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]
Shape of reshape of array b is: (16, 1)
Size of reshape of array b is: 16


We can also take transpose of array (for the same shape, better to use this method, reshape doesn't work at all):

In [0]:
array_b_T = array_b.T
print(f"Transpose of array b is:\n{array_b_T}")
print(f"Shape of transpose of array b is: {array_b_T.shape}")
print(f"Size of transpose of array b is: {array_b_T.size}", "\n")

print("Proving that reshape doesn't work for the same shape:")
print(f"Reshape of array b to 4x4 is:\n{array_b.reshape(4, 4)}")
print(f"Ärray b is:\n{array_b}")

Transpose of array b is:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Shape of transpose of array b is: (4, 4)
Size of transpose of array b is: 16 

Proving that reshape doesn't work for the same shape:
Reshape of array b to 4x4 is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Ärray b is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Indexing for array:

In [0]:
print(array_b[0])
print(array_b[:,1])
print(array_b[2, 0])

[1 2 3 4]
[ 2  6 10 14]
9


Creating default array with specified data type:

In [0]:
array_c = np.array([[1, 2, 3], [5, 6, 7], [8, 9, 10], [11, 12, 13]], dtype=float)
print(f"Ärray c is:\n{array_c}")

Ärray c is:
[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]
 [11. 12. 13.]]


We can create zeroes, ones, or any other value array:

In [0]:
print(np.zeros((5, 5)), "\n")
print(np.ones((2, 2)), "\n")
print(np.full((5,5), 5), "\n")
print(np.random.random((2, 2)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1.]
 [1. 1.]] 

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]] 

[[0.72267376 0.72628531]
 [0.30413391 0.1004011 ]]


Boolean indexing:

In [0]:
print(f"Ärray c is:\n{array_c}", "\n")

array_c_even = array_c % 2 == 0
print(f"Position of even numbers in array c:\n{array_c_even}", "\n")

array_c_even_no_threes = np.logical_and(array_c % 2 == 0, array_c % 3 != 0) #to use 2 conditions
print(f"Position of even numbers that are not divisible by 3 in array c:\n{array_c_even_no_threes}")

Ärray c is:
[[ 1.  2.  3.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]
 [11. 12. 13.]] 

Position of even numbers in array c:
[[False  True False]
 [False  True False]
 [ True False  True]
 [False  True False]] 

Position of even numbers that are not divisible by 3 in array c:
[[False  True False]
 [False False False]
 [ True False  True]
 [False False False]]


To filter the array by condition we use np.where function (first argument is the condition, second argument is the value you want to put into array if the condition is true, third argument is the value you want to put into array if the condition is false) or by logical statement in index:

In [0]:
array_c_odd = np.where(array_c % 2 != 0, array_c, 0)
print(f"Odd numbers in array c:\n{array_c_odd}", "\n")

array_c_odd_no_threes = np.where(np.logical_and(array_c % 2 != 0, array_c % 3 != 0), array_c, 0)
print(f"Odd numbers that are not divisible by 3 in array c:\n{array_c_odd_no_threes}", "\n")

array_c_odd_no_threes_i = array_c[np.logical_and(array_c % 2 != 0, array_c % 3 != 0)]
print(f"Odd numbers that are not divisible by 3 in array c:\n{array_c_odd_no_threes_i}")

Odd numbers in array c:
[[ 1.  0.  3.]
 [ 5.  0.  7.]
 [ 0.  9.  0.]
 [11.  0. 13.]] 

Odd numbers that are not divisible by 3 in array c:
[[ 1.  0.  0.]
 [ 5.  0.  7.]
 [ 0.  0.  0.]
 [11.  0. 13.]] 

Odd numbers that are not divisible by 3 in array c:
[ 1.  5.  7. 11. 13.]


We can sum array elements in total, along row, or column (0 for columns, 1 for rows):

In [0]:
array_d = np.array([[1, 2], [3, 4]], dtype=float)
array_e = np.array([[5, 6], [7, 8]], dtype=float)
print(f"Ärray d is:\n{array_d}", "\n")
print(f"Ärray e is:\n{array_e}", "\n")

print(array_e.sum(axis=0))
print(array_e.sum(axis=1))
print(array_e.sum())

Ärray d is:
[[1. 2.]
 [3. 4.]] 

Ärray e is:
[[5. 6.]
 [7. 8.]] 

[12. 14.]
[11. 15.]
26.0


We can do the same for product:

In [0]:
print(array_e.prod(axis=0))
print(array_e.prod(axis=1))
print(array_e.prod())

[35. 48.]
[30. 56.]
1680.0


We can perform element by element math calculations:

In [0]:
print(array_d + array_e, "\n")
print(array_d - array_e, "\n")
print(array_d * array_e, "\n")
print(array_d / array_e, "\n")
print(np.power(array_d, array_e))

[[ 6.  8.]
 [10. 12.]] 

[[-4. -4.]
 [-4. -4.]] 

[[ 5. 12.]
 [21. 32.]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


Dot product is performed with np.dot function:

In [0]:
print(np.dot(array_d, array_e))

[[19. 22.]
 [43. 50.]]


In [0]:
To find the maximum difference array, minimum value, maximum value, mean value:

In [0]:
print(array_e.ptp())
print(array_e.min())
print(array_e.max())
print(array_e.mean())

3.0
5.0
8.0
6.5
